### ISSUE TITLE
Docking with Macrocycles

### ISSUE THREAD

**Issue by margelb** [gcorso/DiffDock#102]
Does Diffdock work well with macrocylces such as rifampicin and cyclic peptides? Thanks,

**Comment by gcorso** [comment]
Hi Margelb,

Although we have not tested this, my guess would be no. Because DiffDock, in its current version, does not consider flexibility of molecules within cycles, which is problematic when instead there is a lot of natural flexibility as in the case of macrocycles. This will hopefully improve in future versions of DiffDock. If you have experience with macrocycles and would be interested in collaborating to this end, please reach out by email!

Gabriele
