### ISSUE TITLE
running diffdock on 2 GPUs 

### ISSUE THREAD

**Issue by pramodkp** [gcorso/DiffDock#103]
Hi,

When I am running diffdock its just running on GPU 1 whereas 2 GPUs are available. How to run on all available GPUs. Also tell the code to run on GPU number 2.

best 
pramod

**Comment by gcorso** [comment]
Hi @pramodkp 

In its current version DiffDock inference only runs on a single GPU (training is multi-GPU), the easiest way I can see to run on multiple GPUs is to split the CSV file in multiple ones and run each one with its own process. Otherwise one can split the inference itself between multiple GPUs by changing the loader type from `DataLoader` to `DataListLoader` (similar with the model, see training code).

**Comment by pramodkp** [comment]
Hi @gcorso 
Thank you for the answer. 
Can you tell us how to execute the first suggestion  "run on multiple GPUs is to split the CSV file in multiple ones and run each one with its own process"  because when I am dividing the csv into multiple and running python -m inference command it uses the first GPU only for both the csv file.

How to assign GPU/process.

best
Pramod

**Comment by RJ3** [comment]
If you have access to MapReduce then you use the csv as the mapper file.
Alternatively, you could hack a little bit of PyTorch code so that the process runs on a particular GPU.

Either way, you would need to map the different independent data (jobs) to each device.

There are some hints across the web, for example here:
https://stackoverflow.com/questions/54216920/how-to-use-multiple-gpus-in-pytorch

**Comment by pramodkp** [comment]
Thanks for the suggestion @RJ3

**Comment by gcorso** [comment]
The easiest way I know is to simply add before every command `CUDA_VISIBLE_DEVICES="1" python ...` where the GPUs are typically numbered from 0 to 7 (or 3). This will execute your command only on the second GPU. Therefore if you split the csv and run the commands with different ids, it should run them on different GPUs
