### ISSUE TITLE
Optimizing for time

### ISSUE THREAD

**Issue by iamick-postera** [gcorso/DiffDock#12]
As the code is written (--inference_steps 20 --samples_per_complex 40 --batch_size 10), it takes about 12 minutes/run to complete on a Mac M1 with 32 GB RAM. I have tried to minimize these values but have gotten less accurate results. Can you provide some insight into which parameters can be minimized without losing significant accuracy?

**Comment by gcorso** [comment]
Hi,
In general, whenever possible we suggest running on GPUs since, as for most deep learning models, they provide huge speedups. However, to obtain speedups on the same hardware, you can set --samples_per_complex 10 to get a 4x speedup at little performance cost (top1 accuracy 38% -> 35%). Then, for further speedup you can probably safely reduce up to 10 the inference steps. The batch size is only relevant when having a larger number of samples per complex.
I hope this helps
