### ISSUE TITLE
Question about the sde schedule

### ISSUE THREAD

**Issue by zhuole1025** [gcorso/DiffDock#144]
Hi, thanks for your amazing work! After reading your Diffdock paper and running the code, I am curious why you chose the VE-SDE for the score model. Have you tried other SDEs like VP and the one in the EDM paper? Will the schedule greatly affect the sample quality due to the different weights on exploring and refinement stages?

**Comment by gcorso** [comment]
Hi, no very strong reason, we used VE-SDE because I believe it is the one that makes the most sense for the SO(2) and SO(3) diffusion components (I might be wrong ofc) and we kept the same for the Euclidean component as well. We did not try the VP SDE or other variations so I'm not sure how it would change the performance

**Comment by zhuole1025** [comment]
Thanks for your response!
