### ISSUE TITLE
How to train with multiple GPUs?

### ISSUE THREAD

**Issue by amorehead** [gcorso/DiffDock#156]
Hello.

Thanks for making this great work publicly available. I was curious, how can one train a new copy e.g., of the score model using multiple GPUs? I see you all are using PyTorch Geometric's `DataParallel` class to handle distributed training. However, in certain key locations of the training code it looks like the device `cuda:0` is hard-coded, so I am a bit confused e.g., which command one can run to launch `train.py` with multiple GPUs.

https://github.com/gcorso/DiffDock/blob/600a23fa23e25d9628840695c8ba55f01111ebff/train.py#L157

Best,
Alex

**Comment by vsomnath** [comment]
Not a contributor, but having worked a bit with the codebase and also PyTorch Geometric DataParallel (https://pytorch-geometric.readthedocs.io/en/latest/_modules/torch_geometric/nn/data_parallel.html), here's what is happening

`DataParallel` automatically scatters your batch across multiple GPUs, and creates replicas of the model on each of those. There is a a device check happening in the `pyg.DataParallel` class in the `forward` method, and this expects the model and its parameters to be on `cuda:0` which is why the hard-coding.

**Comment by amorehead** [comment]
I see. Thanks for pointing this out. Then, do we need to specify for `pyg.DataParallel` which (or how many) devices to use during training, or will it automatically use all available GPUs for data-parallel training?

**Comment by vsomnath** [comment]
It automatically uses it - atleast this is what I have been seeing so far!
