### ISSUE TITLE
Question about translation score

### ISSUE THREAD

**Issue by ShoufaChen** [gcorso/DiffDock#18]
Hi,

Would you please give some hints about the calculation process of the translation score?

Thanks in advance.

https://github.com/gcorso/DiffDock/blob/f6094e747114e7f2e25b103ecaad80e78ffbb0b3/datasets/pdbbind.py#L50

**Comment by gcorso** [comment]
Hi @ShoufaChen 
This is just a normalization factor that we apply to the translation score prediction. 
Intuitively, under the assumption that the data is a Dirac, it makes the prediction vector that the model needs to predict independent of the score (think about it as predicting the translation vector to the true location). We have found this normalization to work slightly better than the one that is typically applied to score models (multiplying by the expected norm of the score at every timestep).

**Comment by ShoufaChen** [comment]
Hi @gcorso 

Thanks for your reply but I am still confused by this formula.

Specifically, why do you choose `tr_sigma ** 2` as the normalization factor?

Besides, what is `tr_score`? Is there any formula in the paper that corresponds to this procedure?

**Comment by gcorso** [comment]
Because if you have a zero-centered Gaussian with variance sigma2, the score at some displacement x is -2x/sigma2. Therefore we ask the model to predict -2x and obtain the score dividing by sigma2.

tr_sigma is simply the standard deviation (square root of the variance) in the translation component of the diffusion. Usually, in diffusion models, it is just indicated by sigma but we need to distinguish the variances of the kernels in the different components (indicated by tr_, rot_ and tor_)
