### ISSUE TITLE
DiffDock command line argument

### ISSUE THREAD

**Issue by KeaunAmani** [gcorso/DiffDock#207]
I would like to know the following about some of the command line arguments DiffDock uses:

For `inference_steps` & `actual_steps` what are the recommended values and does increasing or decreasing these values improve performance? Also what do these options do?

Does `no_final_step_noise` improve accuracy?

**Comment by MurtoHilali** [comment]
From the paper and code itself, I was able to ascertain the following:

- `inference_steps` and `actual_steps` refer to the number of iterative steps the model will take (given a complex) in its reverse diffusion process to actually dock your ligand.
- `inference_steps` will be the number of steps used unless otherwise specified by `actual_steps`, seen here in line 261 of `inference.py`:

https://github.com/gcorso/DiffDock/blob/b4704d94de74d8cb2acbe7ec84ad234c09e78009/inference.py#L261

- default values (20 steps) are good, but if you're looking to improve runtime you can reduce the number of steps to ~10 without a noticeable loss in accuracy, according to the paper: "We note that the model reaches nearly the full performance even with just 10 steps, suggesting that the model can be sped up 2x with a small drop in accuracy"

<img width="442" alt="Screenshot 2024-10-10 at 3 48 18 PM" src="https://github.com/user-attachments/assets/06cb5d19-638a-4b95-8fd2-4c3a5dd0f7c3">

Hope this is helpful!

**Comment by KeaunAmani** [comment]
Thank you for your answer @MurtoHilali. This was indeed helpful.
