### ISSUE TITLE
ModuleNotFoundError: No module named 'esm.model'

### ISSUE THREAD

**Issue by akshat998** [gcorso/DiffDock#25]
Hello, 

Thank you for the great work. I was trying the example out of the box. Namely (I managed to successfully clone the repo & install the conda environment). Then, I ran:

```
python datasets/esm_embedding_preparation.py --protein_ligand_csv data/protein_ligand_example_csv.csv --out_file data/prepared_for_esm.fasta 
git clone https://github.com/facebookresearch/esm
cd esm
pip install -e .
cd ..
HOME=esm/model_weights python esm/scripts/extract.py esm2_t33_650M_UR50D data/prepared_for_esm.fasta data/esm2_output --repr_layers 33 --include per_tok 
```

However, on the last line of code, I received the error: 

```
(diffdock) akshat@Akshat:~/Downloads/DiffDock$ HOME=esm/model_weights python esm/scripts/extract.py esm2_t33_650M_UR50D data/prepared_for_esm.fasta data/esm2_output --repr_layers 33 --include per_tok
Traceback (most recent call last):
  File "/home/akshat/Downloads/DiffDock/esm/scripts/extract.py", line 12, in <module>
    from esm import Alphabet, FastaBatchedDataset, ProteinBertModel, pretrained, MSATransformer
  File "/home/akshat/Downloads/DiffDock/esm/esm/pretrained.py", line 15, in <module>
    from esm.model.esm2 import ESM2
ModuleNotFoundError: No module named 'esm.model'
```

I would appreciate some advice. 

Thank you so much! :)

**Comment by HannesStark** [comment]
To me this sounds like the installation did not go through successfully.
Are you sure that `pip install -e .` worked?

also make sure that the esm directory is inside the DiffDock directory

**Comment by jw-feng** [comment]
I am also running into this error. I can confirm that `pip install -e .` worked as shown in the output below

DiffDock/esm$ pip install -e .
Defaulting to user installation because normal site-packages is not writeable
Obtaining file:///home/jwfeng/DiffDock/esm
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Building wheels for collected packages: fair-esm
  Building editable for fair-esm (pyproject.toml) ... done
  Created wheel for fair-esm: filename=fair_esm-2.0.0-0.editable-py3-none-any.whl size=15609 sha256=563a7d26bf1fc69acec2728576c34d5a8a2f0413e7ece9b96ca8874c5f966875
  Stored in directory: /tmp/pip-ephem-wheel-cache-l1vhzzhp/wheels/78/23/40/de59da61f4dde966143b7d99afbba0198e237a8e01216d41b6
Successfully built fair-esm
Installing collected packages: fair-esm
  Attempting uninstall: fair-esm
    Found existing installation: fair-esm 2.0.0
    Uninstalling fair-esm-2.0.0:
      Successfully uninstalled fair-esm-2.0.0
Successfully installed fair-esm-2.0.0

**Comment by gcorso** [comment]
Great, thanks for the update!
