### ISSUE TITLE
 'NoneType' object has no attribute 'RemoveAllConformers'

### ISSUE THREAD

**Issue by jadolfbr** [gcorso/DiffDock#26]
Running on the example works fine. 
Running on new structures in a csv file with full paths/etc.  I get this error(even though I'm not running PDBBind data):

Run cmd:
```
python -m inference --protein_ligand_csv data/diffdock_paths.csv  --out_dir results/glycans_local --inference_steps 20 --samples_per_complex 40 --batch_size 10
```

```
 File "/home/jadolfbr/.conda/envs/diffdock/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/jadolfbr/.conda/envs/diffdock/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/jadolfbr/DiffDock/inference.py", line 81, in <module>
    test_dataset = PDBBind(transform=None, root='', protein_path_list=protein_path_list, ligand_descriptions=ligand_descriptions,
  File "/home/jadolfbr/DiffDock/datasets/pdbbind.py", line 102, in __init__
    self.inference_preprocessing()
  File "/home/jadolfbr/DiffDock/datasets/pdbbind.py", line 208, in inference_preprocessing
    mol.RemoveAllConformers()
AttributeError: 'ValueError' object has no attribute 'RemoveAllConformers'
```

**Comment by gcorso** [comment]
Hi @jadolfbr,
Sorry for the delay. For the first issue it seems that the problem was that in the `read_molecule` routine we were returning an error instead of raising it. It seems that you are using an input file not supported. What type of file are you using for the input? (at the moment `.mol2, .sdf, .pdbqt` and `.pdb` should be the ones working) If the ligand file is a `.pdb`, would it be possible for you to send us an exemplary file to figure out why the RDkit routine returns an error instead of an RDkit molecule? 
The second issue should also be connected to this.

**Comment by jadolfbr** [comment]
Sure, will send inputs.  Email? These were both .pdb files.

**Comment by gcorso** [comment]
gcorso@mit.edu and hstark@mit.edu

**Comment by HannesStark** [comment]
To address this for everyone, this happens if RDKit is unable to read the ligand file, then returns None and then the function call fails. I now added a check for whether RDKit was unable to read the molecule to at least log when the issue is happening.
However, I am not sure why exactly RDKit is unable to read some files. Potentially there might be some issues with files like this.
