### ISSUE TITLE
Cannot create a consistent method resolution order (MRO) for bases Batch, Batch

### ISSUE THREAD

**Issue by YonggangZhangUSTC** [gcorso/DiffDock#30]
Hi,
Thank you for the great project!

I followed the readme to taste the project but got confusing issues:

"Failed on [xxx] Cannot create a consistent method resolution order (MRO) for bases Batch, Batch"
when I run "Using the provided model weights for evaluation," i.e., 
python -m inference --protein_ligand_csv data/testset_csv.csv --out_dir results/user_predictions_testset --inference_steps 20 --samples_per_complex 40 --batch_size 10 --actual_steps 18 --no_final_step_noise

Would you mind giving some comments/suggestions to solve this problem?

**Comment by HannesStark** [comment]
Hi,

I have never seen the error "Cannot create a consistent method resolution order (MRO) for bases Batch, Batch"

For debugging this I would recommend going to the line where "Failed on [xxx]" is printed and raising the error instead of just printing it and continuing the execution.

Please let us know if you can resolve it like this or if that provides more details!

**Comment by gcorso** [comment]
I will close this issue for inactivity, please reopen it if the problem persists

**Comment by hamzaibrahim21** [comment]
Hi all,

It happened also to me. When I raised the error, I found out that torch-geometric was outdated.

When updated to 2.3.1 by installing `pip install torch-geometric==2.3.1`, it worked fine.
