### ISSUE TITLE
Index typo in the model

### ISSUE THREAD

**Issue by luwei0917** [gcorso/DiffDock#34]
Thanks for the great work!

We notice a potentially major typo in the code. 

https://github.com/gcorso/DiffDock/blob/f8d67b5b2b30b72eedd010e76accc1a306ee605f/models/score_model.py#L298

center_edge_index[0] will give us data['ligand'].batch (as defined below) 

https://github.com/gcorso/DiffDock/blob/f8d67b5b2b30b72eedd010e76accc1a306ee605f/models/score_model.py#L403

But this doesn't make sense here. since we don't need the features from the graph for protein/ligand pair 0 to make prediction for protein/ligand pair 1. But lig_node_attr has dimension n_atom x n_feature. meaning that pair 1 will get features from pair 0. 

This typo should have large effect on the result, but somehow it doesn't look like so. so we are confused. Maybe our understanding is not correct.

Wei

**Comment by gcorso** [comment]
Hi @luwei0917 

Great catch! Indeed it seems that on line 298 it should have been `center_edge_index[1]` not `center_edge_index[0]`. What is happening in line 298 is that we give as edge features in the final convolution not only the actual features of the edge (e.g. the encoding of the distance) but also the scalar embedding of the node from which the message is coming. 
Since I put the wrong index the node features that were being provided to the edge will be of a "random" node. 

In my understanding this will lead us to the network just learning to ignore those reducing the tensor convolution to one using edge features only to compute the product weights (which is what is often done anyways), this is why I expect the results to be very similar if this is fixed for inference only. This being said we are currently running both inference with the previously trained model and the fix and a new training run with the fixed model. We expect the latter to have performance better or similar to the previous model (we will just be providing more info to the model). 

Thank you very much for the catch and for letting us know,
Gabriele

**Comment by gcorso** [comment]
Indeed inference with the previously trained model already obtains slightly better results than those on the manuscript. We will update the repo code soon and add an acknowledgment!

**Comment by gcorso** [comment]
Fixed! In our experiments, however, the performance difference was not statistically significant.
Thank you very much again for raising the issue!
