### ISSUE TITLE
What is the difference between score model and confidence model？

### ISSUE THREAD

**Issue by lonngxiang** [gcorso/DiffDock#53]
when Training a model by myself， What is the difference between score model and confidence model？ why need this two score

**Comment by lonngxiang** [comment]
is large score model or small score model Refers to the https://github.com/gcorso/DiffDock/blob/main/workdir/paper_score_model/best_ema_inference_epoch_model.pt ？and   The result of running python -m confidence.confidence_train is   https://github.com/gcorso/DiffDock/blob/main/workdir/paper_confidence_model/best_model_epoch75.pt ？

**Comment by gcorso** [comment]
Correct regarding the location, regarding the difference between the two: 
- the score model is used to generated a number of poses via the diffusion process, note that it is called score, not because it predicts a score, but because it predicts the score of the distribution which is the gradient of the log density function (think about it as a force)
- the confidence model instead is trying to determine how good the poses generated are

I hope this helps and I suggest to read the paper for more details!
Gabriele

**Comment by lonngxiang** [comment]
> * score

So the Score Model here is the Score
Diffusion Model?

**Comment by lonngxiang** [comment]
> Correct regarding the location, regarding the difference between the two:
> 
> * the score model is used to generated a number of poses via the diffusion process, note that it is called score, not because it predicts a score, but because it predicts the score of the distribution which is the gradient of the log density function (think about it as a force)
> * the confidence model instead is trying to determine how good the poses generated are
> 
> I hope this helps and I suggest to read the paper for more details! Gabriele

So the Score Model here is the Score
Diffusion Model?

**Comment by gcorso** [comment]
Yes in the literature of diffusion models, the model predicting the gradient of the log density of the data (i.e. the score) is called "score model"
