### ISSUE TITLE
Failed to read molecule

### ISSUE THREAD

**Issue by pramodkp** [gcorso/DiffDock#62]
getting the the below error while using canonical smiles.

13it [00:08,  1.23it/s]rdkit coords could not be generated without using random coords. using random coords no
13it [00:20,  1.23it/s]Failed to read molecule  COC(=O)[C@]1(C)CCN(C(=O)C2[C@H]3CCC[C@H]23)C1  We are skippingThe reason is the exception:  Bad Conformer Id

I am trying to run big ligand library against a protein but it is failing to read molecule. 
Also is there any limit for the number of complex can be try at a time.

regards
Pramod

**Comment by gcorso** [comment]
Hi,
the problem is that RDKit has issues with embedding that molecule (both using RDKit ETKDG and by optimising randomly initialized coordinates), without a starting geometry DiffDock cannot run. If you have some way of embedding the molecule in 3D you could add it to the code in process_mols.py where the ligands are embedded in 3D.

There is no limit on the number of complexes to be docked except the time it takes on your hardware :)

I hope this helps,
Gabriele
