### ISSUE TITLE
Support for Peptide and Protein Binding

### ISSUE THREAD

**Issue by Leo-T-Zang** [gcorso/DiffDock#71]
Hi,

Thank you for the amazing work.

I want to ask if DiffDock supports peptide and protein docking. Thank you!

**Comment by RJ3** [comment]
It should work in theory if the peptide is small enough but there are a few problems. DiffDock typically expects the ligand in mol2, sdf, or SMILES. In theory other formats supported by RDKit could work. I've run into problems converting PDBs into SDF using something like OpenBabel and Phenix/Elbow. I cannot get past the valency error from RDKit processing.

Try it out and let me know what you find. An alternative for this problem is EquiDock.

**Comment by gcorso** [comment]
For small peptides, DiffDock should already work as is as @RJ3 mentioned, although of course fine-tuning of peptide binding data would help. For protein-protein docking, we will have an update coming out soon!
